# Descarga de imagenes - Fase 1

In [1]:
import pandas as  pd 
import urllib.request
import datetime
import os
import shutil
import requests

C:\Users\m.alvarezg1\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\m.alvarezg1\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\m.alvarezg1\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [24]:
unpickled_df = pd.read_pickle("E:/TesisMA/Datos/datatotal",compression="gzip")
unpickled_df

,id,ascensor,banos,banoservicio,barriocomun,ciudad,codigoweb,conjuntocerrado,cuartoservicio,deposito,...,scanombre,scacodigo,mancodigo,lotcodigo,cpob_ccdgo,setu_ccnct,secu_ccnct,areaconstruida,areaprivada,arealote
0,1.0,None,NaN,None,None,None,None,None,None,None,...,TEUSAQUILLO,007104,None,None,11001000,110011000000007104,11001100000000710401,700,700,NaN
1,4.0,None,NaN,None,None,None,None,None,None,None,...,BOSQUE DE PINOS III,008538,008538029,008538029031,11001000,110011000000008535,11001100000000853506,107.81,107.81,NaN
2,6.0,None,NaN,None,None,None,None,None,None,None,...,BATAN,009118,009118005,009118005002,11001000,110011000000009118,11001100000000911803,92.9,92.9,NaN
3,8.0,None,NaN,None,None,None,None,None,None,None,...,ALCAZARES,007302,007302026,007302026004,11001000,110011000000007302,11001100000000730201,126,110,NaN
4,9.0,None,NaN,None,None,None,None,None,None,None,...,TUNDAMA,004515,None,None,11001000,110011000000004518,11001100000000451807,65,65,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84469,1893288.0,None,5.0,None,None,Medellín,15519-1679,None,None,False,...,None,None,None,None,05001000,050011000000001203,05001100000000120301,0.0,None,NaN
84470,1893289.0,None,1.0,None,None,Medellín,15666-1281176,None,None,True,...,None,None,None,None,05001000,050011000000001112,05001100000000111204,27.0,None,NaN
84471,1893290.0,None,1.0,None,None,Medellín,14967-1963118,None,None,True,...,None,None,None,None,05001000,050011000000001105,05001100000000110501,45.08,None,NaN
84472,1893291.0,None,1.0,None,None,Medellín,14967-1963135,None,None,True,...,None,None,None,None,05001000,050011000000001105,05001100000000110501,50.66,None,NaN
84473,1893292.0,None,NaN,True,None,Medellín,7264-1744,None,None,False,...,None,None,None,None,05001000,050011000000001105,05001100000000110501,63.7,None,NaN

In [25]:
unpickled_df.columns

Index(['id', 'ascensor', 'banos', 'banoservicio', 'barriocomun', 'ciudad',
       'codigoweb', 'conjuntocerrado', 'cuartoservicio', 'deposito',
       'descripcion', 'estado', 'estrato', 'estudio', 'fecha_inicial',
       'fecha_final', 'garajes', 'gimnasio', 'habitaciones', 'halldealcobas',
       'imagenes', 'inmobiliaria', 'label', 'latitud', 'longitud',
       'nombreempresa', 'parqueaderovisitantes', 'piscina', 'piso', 'porteria',
       'remodelado', 'saloncomunal', 'telefono1', 'telefono2', 'telefono3',
       'telefono4', 'telefono5', 'tiempodeconstruido', 'tipoinmueble',
       'tiponegocio', 'url', 'valoradministracion', 'valorarriendo',
       'valorventa', 'vigilancia', 'vista', 'zonalavanderia', 'fuente',
       'areaconstruidastr', 'areaprivadastr', 'balcon', 'direccion', 'niveles',
       'terraza', 'ultimopiso', 'valor', 'valoradministracionstr',
       'valorarriendostr', 'valorstr', 'valorventastr', 'arealotestr',
       'vetustez', 'antiguedad', 'dpto_ccdgo', 'dpto_cnmbr', 'mpio_ccdgo',
       'mpio_cnmbr', 'locnombre', 'loccodigo', 'upzcodigo', 'upznombre',
       'upznumero', 'scanombre', 'scacodigo', 'mancodigo', 'lotcodigo',
       'cpob_ccdgo', 'setu_ccnct', 'secu_ccnct', 'areaconstruida',
       'areaprivada', 'arealote'],
      dtype='object')

In [26]:
filtrados = unpickled_df[((unpickled_df["tipoinmueble"] == "Apartamento")  | (unpickled_df["tipoinmueble"] == "Casa"))
                    & (unpickled_df["fuente"] == "M2") ] 
filtrados

,id,ascensor,banos,banoservicio,barriocomun,ciudad,codigoweb,conjuntocerrado,cuartoservicio,deposito,...,scanombre,scacodigo,mancodigo,lotcodigo,cpob_ccdgo,setu_ccnct,secu_ccnct,areaconstruida,areaprivada,arealote
2,6.0,None,NaN,None,None,None,None,None,None,None,...,BATAN,009118,009118005,009118005002,11001000,110011000000009118,11001100000000911803,92.9,92.9,NaN
3,8.0,None,NaN,None,None,None,None,None,None,None,...,ALCAZARES,007302,007302026,007302026004,11001000,110011000000007302,11001100000000730201,126,110,NaN
4,9.0,None,NaN,None,None,None,None,None,None,None,...,TUNDAMA,004515,None,None,11001000,110011000000004518,11001100000000451807,65,65,NaN
5,10.0,None,NaN,None,None,None,None,None,None,None,...,MIRANDELA,009133,009133019,009133019013,11001000,110011000000009119,11001100000000911903,560,560,NaN
7,16.0,None,NaN,None,None,None,None,None,None,None,...,SANTA BARBARA CENTRAL,008415,008415042,008415042016,11001000,110011000000008415,11001100000000841508,60,60,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14581,1891605.0,None,1.0,None,PASOANCHO,Cali,11554-2746405,None,None,None,...,None,None,None,None,76001000,760011000000001004,76001100000000100401,35.0,35.0,NaN
14582,1891606.0,True,2.0,None,BILBAO,Bogotá D.C.,839-360244,True,None,None,...,TIBABUYES II,009248,009248007,009248007073,11001000,110011000000009222,11001100000000922205,58.0,58.0,NaN
14584,1891608.0,True,2.0,None,Via 19,Armenia,12293-M2860044,True,None,True,...,None,None,None,None,None,None,None,60.0,60.0,NaN
14586,1891610.0,True,2.0,None,La Loma Del Indio,Medellín,11166-M2864421,None,None,None,...,None,None,None,None,05001000,050011000000000911,05001100000000091102,65.0,65.0,NaN
14587,1891611.0,True,2.0,None,CHAPINERO,Bogotá D.C.,11013-22747,None,None,None,...,CHAPINERO CENTRAL,008213,None,None,11001000,110011000000008213,11001100000000821302,46.0,0.0,NaN

In [33]:
filtrados_Bogota = filtrados[filtrados["ciudad"]=="Bogotá D.C."]
filtrados_Bogota.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 92844 entries, 189128 to 14587
Data columns (total 82 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      92844 non-null  float64
 1   ascensor                46345 non-null  object
 2   banos                   92732 non-null  float64
 3   banoservicio            2232 non-null   object
 4   barriocomun             92730 non-null  object
 5   ciudad                  92844 non-null  object
 6   codigoweb               92844 non-null  object
 7   conjuntocerrado         39015 non-null  object
 8   cuartoservicio          17128 non-null  object
 9   deposito                29012 non-null  object
 10  descripcion             92719 non-null  object
 11  estado                  92844 non-null  object
 12  estrato                 92212 non-null  float64
 13  estudio                 32588 non-null  object
 14  fecha_inicial           85296 non-null  object
 15  fecha_final             85296 non-null  object
 16  garajes                 92736 non-null  float64
 17  gimnasio                22103 non-null  object
 18  habitaciones            92678 non-null  float64
 19  halldealcobas           24975 non-null  object
 20  imagenes                92844 non-null  object
 21  inmobiliaria            80668 non-null  object
 22  label                   92844 non-null  object
 23  latitud                 92844 non-null  float64
 24  longitud                92844 non-null  float64
 25  nombreempresa           0 non-null      object
 26  parqueaderovisitantes   8238 non-null   object
 27  piscina                 6874 non-null   object
 28  piso                    64750 non-null  float64
 29  porteria                9468 non-null   object
 30  remodelado              2806 non-null   object
 31  saloncomunal            42053 non-null  object
 32  telefono1               92724 non-null  object
 33  telefono2               84149 non-null  object
 34  telefono3               0 non-null      object
 35  telefono4               0 non-null      object
 36  telefono5               0 non-null      object
 37  tiempodeconstruido      92773 non-null  object
 38  tipoinmueble            92844 non-null  object
 39  tiponegocio             92844 non-null  object
 40  url                     92844 non-null  object
 41  valoradministracion     73137 non-null  object
 42  valorarriendo           64326 non-null  object
 43  valorventa              69861 non-null  object
 44  vigilancia              59426 non-null  object
 45  vista                   0 non-null      object
 46  zonalavanderia          54680 non-null  object
 47  fuente                  92844 non-null  object
 48  areaconstruidastr       0 non-null      object
 49  areaprivadastr          0 non-null      object
 50  balcon                  0 non-null      object
 51  direccion               0 non-null      object
 52  niveles                 0 non-null      float64
 53  terraza                 0 non-null      object
 54  ultimopiso              0 non-null      object
 55  valor                   0 non-null      object
 56  valoradministracionstr  0 non-null      object
 57  valorarriendostr        0 non-null      object
 58  valorstr                0 non-null      object
 59  valorventastr           0 non-null      object
 60  arealotestr             0 non-null      object
 61  vetustez                0 non-null      float64
 62  antiguedad              0 non-null      float64
 63  dpto_ccdgo              91896 non-null  object
 64  dpto_cnmbr              91896 non-null  object
 65  mpio_ccdgo              91896 non-null  object
 66  mpio_cnmbr              91896 non-null  object
 67  locnombre               91861 non-null  object
 68  loccodigo               91861 non-null  object
 69  upzcodigo               91615 non-null  object
 70  upznombre               91615 non-null  object
 71  upznumero               91477 non-null  float64
 72  scanombre               91856 non-null  object
 73  scacodigo               91856 non-null  object
 74  mancodigo               66021 non-null  object
 75  lotcodigo               77419 non-null  object
 76  cpob_ccdgo              91538 non-null  object
 77  setu_ccnct              91538 non-null  object
 78  secu_ccnct              91538 non-null  object
 79  areaconstruida          92784 non-null  object
 80  areaprivada             92783 non-null  object
 81  arealote                0 non-null      float64
dtypes: float64(13), object(69)
memory usage: 58.8+ MB

In [60]:
data_Bogota_final=filtrados_Bogota[["id","tipoinmueble","banos","estado","estrato","garajes","habitaciones","piso","tiempodeconstruido"
                                    ,"areaconstruida","latitud","longitud","valorventa","imagenes"]]
data_Bogota_final=data_Bogota_final.dropna()
data_Bogota_final

,id,tipoinmueble,banos,estado,estrato,garajes,habitaciones,piso,tiempodeconstruido,areaconstruida,latitud,longitud,valorventa,imagenes
189128,721536.0,Apartamento,2.0,Usado,3.0,1.0,3.0,3.0,Entre 5 y 10 años,76.0,4.751413,-74.091550,289000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189129,721537.0,Apartamento,2.0,Usado,4.0,1.0,3.0,5.0,Entre 5 y 10 años,72.0,4.648093,-74.103546,450000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189130,721538.0,Apartamento,4.0,Usado,6.0,2.0,3.0,3.0,Entre 10 y 20 años,220.0,4.708651,-74.025696,1300000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189133,721541.0,Apartamento,3.0,Usado,6.0,2.0,2.0,4.0,Entre 0 y 5 años,120.0,4.680367,-74.052155,1150000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189134,721542.0,Apartamento,1.0,Usado,3.0,1.0,3.0,3.0,Entre 10 y 20 años,55.86,4.636661,-74.125410,260000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14558,1891581.0,Apartamento,1.0,Usado,3.0,0.0,2.0,24.0,Entre 0 y 5 años,41.9,4.583887,-74.156044,130000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14563,1891586.0,Casa,2.0,Usado,2.0,0.0,3.0,2.0,Entre 10 y 20 años,73.0,4.533765,-74.083990,60000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14570,1891593.0,Apartamento,2.0,Usado,2.0,0.0,3.0,6.0,Entre 10 y 20 años,47.0,4.653697,-74.155106,117425000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14576,1891599.0,Casa,2.0,Usado,2.0,0.0,5.0,2.0,Más de 20 años,148.0,4.568058,-74.080020,150000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14587,1891611.0,Apartamento,2.0,Usado,3.0,1.0,1.0,9.0,Entre 0 y 5 años,46.0,4.645788,-74.063900,320000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."

In [2]:
data_Bogota_final.to_pickle("C:/Users/m.alvarezg1/Downloads/dataF2_MC.pkl")

NameError: name 'data_Bogota_final' is not defined

In [4]:
def descargar(datos,start, end):
    global ruta
    data=datos
    global inmueble
    for inmueble in range(start,end):
        urls=data["imagenes"].iloc[inmueble]
        urlsList = urls[1:len(urls)-1].replace('"','').split(",")
        cont =0 
        for url in urlsList:
            cont = cont +1
            urllib.request.urlretrieve(url, ruta
                                       +data["tipoinmueble"].iloc[inmueble]+str(int(data["id"].iloc[inmueble]))+"_"+str(cont)+".jpg")

In [8]:
ruta = "C:/Users/m.alvarezg1/Documents/DataU/"
descargar(filtrados,1025,1120)

In [9]:
def descargarDataPrueba(datos,start, end):
    global ruta
    data=datos
    global inmueble
    dires=['bedroom','bathroom','kitchen','living_room','dining_room']
    for inmueble in range(start,end):
        urls=data["imagenes"].iloc[inmueble]
        urlsList = urls[1:len(urls)-1].replace('"','').split(",")
        cont =0 
        path = os.path.join(ruta, data["tipoinmueble"].iloc[inmueble]+"_"+str(int(data["id"].iloc[inmueble])))
        os.mkdir(path)
        for d in dires:
            path_d = os.path.join(path, d)
            os.mkdir(path_d)
        for url in urlsList:
            cont = cont +1
            urllib.request.urlretrieve(url, path+
                                       "/"+data["tipoinmueble"].iloc[inmueble]+"_"+str(int(data["id"].iloc[inmueble]))+"_"+str(cont)+".jpg")

In [6]:
ruta = "E:/TesisMA/Datos/DataPrueba/"
descargarDataPrueba(filtrados,1230,1231)

In [10]:
data_Bogota_final=data_Bogota_final[data_Bogota_final["valorventa"]>0]

In [11]:
data_Bogota_final.to_pickle("C:/Users/m.alvarezg1/Downloads/dataF2_MC.pkl")

In [12]:
data_Bogota_final=pd.read_pickle("C:/Users/m.alvarezg1/Downloads/dataF2_MC.pkl")
data_Bogota_final

,id,tipoinmueble,banos,estado,estrato,garajes,habitaciones,piso,tiempodeconstruido,areaconstruida,latitud,longitud,valorventa,imagenes
189128,721536.0,Apartamento,2.0,Usado,3.0,1.0,3.0,3.0,Entre 5 y 10 años,76.0,4.751413,-74.091550,289000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189129,721537.0,Apartamento,2.0,Usado,4.0,1.0,3.0,5.0,Entre 5 y 10 años,72.0,4.648093,-74.103546,450000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189130,721538.0,Apartamento,4.0,Usado,6.0,2.0,3.0,3.0,Entre 10 y 20 años,220.0,4.708651,-74.025696,1300000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189133,721541.0,Apartamento,3.0,Usado,6.0,2.0,2.0,4.0,Entre 0 y 5 años,120.0,4.680367,-74.052155,1150000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189134,721542.0,Apartamento,1.0,Usado,3.0,1.0,3.0,3.0,Entre 10 y 20 años,55.86,4.636661,-74.125410,260000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14558,1891581.0,Apartamento,1.0,Usado,3.0,0.0,2.0,24.0,Entre 0 y 5 años,41.9,4.583887,-74.156044,130000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14563,1891586.0,Casa,2.0,Usado,2.0,0.0,3.0,2.0,Entre 10 y 20 años,73.0,4.533765,-74.083990,60000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14570,1891593.0,Apartamento,2.0,Usado,2.0,0.0,3.0,6.0,Entre 10 y 20 años,47.0,4.653697,-74.155106,117425000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14576,1891599.0,Casa,2.0,Usado,2.0,0.0,5.0,2.0,Más de 20 años,148.0,4.568058,-74.080020,150000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14587,1891611.0,Apartamento,2.0,Usado,3.0,1.0,1.0,9.0,Entre 0 y 5 años,46.0,4.645788,-74.063900,320000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."

In [18]:
ruta = "E:/TesisMA/DatosF2/"
descargarDataPrueba(data_Bogota_final,1300,1400)

In [15]:
inmueble

1077

In [18]:
filtrados["fecha_final"] = pd.to_datetime(filtrados["fecha_final"])

<ipython-input-18-171bc1fce919>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtrados["fecha_final"] = pd.to_datetime(filtrados["fecha_final"])

,id,ascensor,banos,banoservicio,barriocomun,ciudad,codigoweb,conjuntocerrado,cuartoservicio,deposito,...,scanombre,scacodigo,mancodigo,lotcodigo,cpob_ccdgo,setu_ccnct,secu_ccnct,areaconstruida,areaprivada,arealote
370,762.0,None,NaN,None,None,None,None,None,None,None,...,None,None,None,None,17001000,170011000000000039,17001100000000003901,200,200,NaN

In [122]:
unpickled_df.tail()

,id,ascensor,banos,banoservicio,barriocomun,ciudad,codigoweb,conjuntocerrado,cuartoservicio,deposito,...,scanombre,scacodigo,mancodigo,lotcodigo,cpob_ccdgo,setu_ccnct,secu_ccnct,areaconstruida,areaprivada,arealote
84469,1893288.0,None,5.0,None,None,Medellín,15519-1679,None,None,False,...,None,None,None,None,05001000,050011000000001203,05001100000000120301,0.0,None,NaN
84470,1893289.0,None,1.0,None,None,Medellín,15666-1281176,None,None,True,...,None,None,None,None,05001000,050011000000001112,05001100000000111204,27.0,None,NaN
84471,1893290.0,None,1.0,None,None,Medellín,14967-1963118,None,None,True,...,None,None,None,None,05001000,050011000000001105,05001100000000110501,45.08,None,NaN
84472,1893291.0,None,1.0,None,None,Medellín,14967-1963135,None,None,True,...,None,None,None,None,05001000,050011000000001105,05001100000000110501,50.66,None,NaN
84473,1893292.0,None,NaN,True,None,Medellín,7264-1744,None,None,False,...,None,None,None,None,05001000,050011000000001105,05001100000000110501,63.7,None,NaN

# Descarga de imagenes - Fase 2

In [19]:
data_fase2[data_fase2["inmueble_id"]==data_fase2["inmueble_id"].unique()[8]]

,inmueble_id,url,orden,nid,direccion,tipo_inmueble,latitud,longitud,conjunto_edificio,area,...,tipo_garaje,num_habitaciones,num_ascensores,num_piso,remodelado,ano_remodelacion,tipo_remodelacion,anos_antiguedad,vista_exterior,Vacancia
91,1031191,venta-dwatvvpgfo-16.jpeg,16,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
92,1031191,venta-iiylmpscbi-15.jpeg,15,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
93,1031191,venta-ubtnwmxbuo-8.jpeg,8,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
94,1031191,venta-tdsenhyjbp-5.jpeg,5,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
95,1031191,venta-pgwkvborhg-17.jpeg,17,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
96,1031191,venta-fnzyvagztm-13.jpeg,13,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
97,1031191,venta-zufalxirvd-7.jpeg,7,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
98,1031191,venta-wbssaazgto-6.jpeg,6,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
99,1031191,venta-qkctkxjoza-3.jpeg,3,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
100,1031191,venta-zkyotpzwld-9.jpeg,9,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
101,1031191,venta-parcfhzvat-14.jpeg,14,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
102,1031191,venta-ozngjhpitz-4.jpeg,4,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
103,1031191,venta-sxivrfyvzj-10.jpeg,10,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
104,1031191,venta-zabsxolnmh-2.jpeg,2,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
105,1031191,venta-rvlhanmmkl-11.jpeg,11,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
106,1031191,venta-oyincjlzry-12.jpeg,12,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355
107,1031191,venta-iqhyzbfzzi-1.jpeg,1,1608003164,carrera 102B # 151 - 15,Apartamento,4.750131,-74.09188,Yakali,66,...,independiente,3,2.0,7.0,1.0,2020.0,Parcial,9.0,1.0,355

In [3]:
data_fase2.shape

(6019, 23)

In [4]:
### Crear estructura de directorios
def crearEstrucutura(data):
    global ruta
    inmubles = data["inmueble_id"].unique().tolist()
    dires=['bedroom','bathroom','kitchen','living_room','dining_room']
    for inmu in inmubles:
        path=os.path.join(ruta,"a_"+str(inmu))
        os.mkdir(path)
        for d in dires:
            path_d = os.path.join(path, d)
            os.mkdir(path_d)

In [5]:
ruta = "E:/TesisMA/DatosF2/"
crearEstrucutura(data_fase2)

In [6]:
def descargarDataF2(data):
    global url
    global ruta
    for i in range(0,5):
        url_img = os.path.join(url,data["url"][i])
        path = os.path.join(ruta,"a_"+str(data["inmueble_id"][i]))
        path = os.path.join(path,str(i)+".jpeg")
        print(path)
        with open(path, 'wb') as handle:
            response=requests.get(url_img,headers={'Host': 'habi-sales-images-prod.s3.us-east-2.amazonaws.com','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36'})
            if not response.ok:
                print(response)

            for block in response.iter_content(1024):
                if not block:
                    break

                handle.write(block)

In [9]:
ruta = "E:/TesisMA/DatosF2/"
url="http://habi-sales-images-prod.s3.us-east-2.amazonaws.com"
descargarDataF2(data_fase2)

E:/TesisMA/DatosF2/a_421\0.jpeg
<Response [403]>
E:/TesisMA/DatosF2/a_421\1.jpeg
<Response [403]>
E:/TesisMA/DatosF2/a_421\2.jpeg
<Response [403]>
E:/TesisMA/DatosF2/a_421\3.jpeg
<Response [403]>
E:/TesisMA/DatosF2/a_421\4.jpeg
<Response [403]>