In [1]:
import pandas as pd
import numpy as np

from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import RandomForestRegressor

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

C:\Users\m.alvarezg1\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\m.alvarezg1\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\m.alvarezg1\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [6]:
data = pd.read_pickle("C:/Users/m.alvarezg1/Downloads/dataF2_MC.pkl")
data

,id,tipoinmueble,banos,estado,estrato,garajes,habitaciones,piso,tiempodeconstruido,areaconstruida,latitud,longitud,valorventa,imagenes
189128,721536.0,Apartamento,2.0,Usado,3.0,1.0,3.0,3.0,Entre 5 y 10 años,76.0,4.751413,-74.091550,289000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189129,721537.0,Apartamento,2.0,Usado,4.0,1.0,3.0,5.0,Entre 5 y 10 años,72.0,4.648093,-74.103546,450000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189130,721538.0,Apartamento,4.0,Usado,6.0,2.0,3.0,3.0,Entre 10 y 20 años,220.0,4.708651,-74.025696,1300000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189133,721541.0,Apartamento,3.0,Usado,6.0,2.0,2.0,4.0,Entre 0 y 5 años,120.0,4.680367,-74.052155,1150000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189134,721542.0,Apartamento,1.0,Usado,3.0,1.0,3.0,3.0,Entre 10 y 20 años,55.86,4.636661,-74.125410,260000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14558,1891581.0,Apartamento,1.0,Usado,3.0,0.0,2.0,24.0,Entre 0 y 5 años,41.9,4.583887,-74.156044,130000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14563,1891586.0,Casa,2.0,Usado,2.0,0.0,3.0,2.0,Entre 10 y 20 años,73.0,4.533765,-74.083990,60000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14570,1891593.0,Apartamento,2.0,Usado,2.0,0.0,3.0,6.0,Entre 10 y 20 años,47.0,4.653697,-74.155106,117425000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14576,1891599.0,Casa,2.0,Usado,2.0,0.0,5.0,2.0,Más de 20 años,148.0,4.568058,-74.080020,150000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
14587,1891611.0,Apartamento,2.0,Usado,3.0,1.0,1.0,9.0,Entre 0 y 5 años,46.0,4.645788,-74.063900,320000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."

In [7]:
data=data[data["valorventa"]>0]
data=data.drop(columns=["estado"])

In [8]:
data = data.iloc[0:20000,]

In [9]:
data

,id,tipoinmueble,banos,estrato,garajes,habitaciones,piso,tiempodeconstruido,areaconstruida,latitud,longitud,valorventa,imagenes
189128,721536.0,Apartamento,2.0,3.0,1.0,3.0,3.0,Entre 5 y 10 años,76.0,4.751413,-74.091550,289000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189129,721537.0,Apartamento,2.0,4.0,1.0,3.0,5.0,Entre 5 y 10 años,72.0,4.648093,-74.103546,450000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189130,721538.0,Apartamento,4.0,6.0,2.0,3.0,3.0,Entre 10 y 20 años,220.0,4.708651,-74.025696,1300000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189133,721541.0,Apartamento,3.0,6.0,2.0,2.0,4.0,Entre 0 y 5 años,120.0,4.680367,-74.052155,1150000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
189134,721542.0,Apartamento,1.0,3.0,1.0,3.0,3.0,Entre 10 y 20 años,55.86,4.636661,-74.125410,260000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
286809,1387944.0,Apartamento,4.0,6.0,3.0,3.0,1.0,Entre 0 y 5 años,270.0,4.660531,-74.049730,3728579250.0,"[""https://metrocuadrado.blob.core.windows.net/..."
286810,1387945.0,Apartamento,5.0,6.0,4.0,3.0,9.0,Entre 0 y 5 años,349.0,4.659425,-74.049770,4500000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
286811,1387946.0,Apartamento,2.0,6.0,1.0,2.0,9.0,Más de 20 años,85.0,4.660799,-74.052414,620000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
286812,1387947.0,Apartamento,5.0,6.0,2.0,4.0,3.0,Más de 20 años,254.0,4.664576,-74.044400,2360000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."
286813,1387948.0,Apartamento,5.0,6.0,0.0,4.0,5.0,Entre 0 y 5 años,358.0,4.663999,-74.045235,3190000000.0,"[""https://metrocuadrado.blob.core.windows.net/..."

In [15]:
labelencoder = LabelEncoder()
enc = OneHotEncoder()
tiempo= labelencoder.fit_transform(data['tiempodeconstruido'])
tiempo = tiempo.reshape(len(tiempo),1)
tiempo = enc.fit_transform(tiempo)
tiempo= pd.DataFrame.sparse.from_spmatrix(tiempo)
tiempo = tiempo.rename(columns={0:'0_5', 1: '10_20',2: '5_10',3:'20_mas'})
tiempo

       0_5  10_20  5_10  20_mas
0      0.0    0.0   1.0     0.0
1      0.0    0.0   1.0     0.0
2      0.0    1.0   0.0     0.0
3      1.0    0.0   0.0     0.0
4      0.0    1.0   0.0     0.0
...    ...    ...   ...     ...
19995  1.0    0.0   0.0     0.0
19996  1.0    0.0   0.0     0.0
19997  0.0    0.0   0.0     1.0
19998  0.0    0.0   0.0     1.0
19999  1.0    0.0   0.0     0.0

[20000 rows x 4 columns]

In [16]:
labelencoder = LabelEncoder()
tipo_inmueble= labelencoder.fit_transform(data['tipoinmueble'])
tipo_inmueble = tipo_inmueble.reshape(len(tipo_inmueble),1)
tipo_inmueble = enc.fit_transform(tipo_inmueble)
tipo_inmueble= pd.DataFrame.sparse.from_spmatrix(tipo_inmueble)
tipo_inmueble = tipo_inmueble.rename(columns={0: 'Apartamento', 1: 'Casa'})
tipo_inmueble

       Apartamento  Casa
0              1.0   0.0
1              1.0   0.0
2              1.0   0.0
3              1.0   0.0
4              1.0   0.0
...            ...   ...
19995          1.0   0.0
19996          1.0   0.0
19997          1.0   0.0
19998          1.0   0.0
19999          1.0   0.0

[20000 rows x 2 columns]

In [17]:
tiempo =tiempo.set_index(data.index)
data[tiempo.columns]=tiempo

tipo_inmueble =tipo_inmueble.set_index(data.index)
data[tipo_inmueble.columns]=tipo_inmueble

data=data.drop(columns=['tiempodeconstruido','tipoinmueble'])
data

,id,banos,estrato,garajes,habitaciones,piso,areaconstruida,latitud,longitud,valorventa,imagenes,0_5,10_20,5_10,20_mas,Apartamento,Casa
189128,721536.0,2.0,3.0,1.0,3.0,3.0,76.0,4.751413,-74.091550,289000000.0,"[""https://metrocuadrado.blob.core.windows.net/...",0.0,0.0,1.0,0.0,1.0,0.0
189129,721537.0,2.0,4.0,1.0,3.0,5.0,72.0,4.648093,-74.103546,450000000.0,"[""https://metrocuadrado.blob.core.windows.net/...",0.0,0.0,1.0,0.0,1.0,0.0
189130,721538.0,4.0,6.0,2.0,3.0,3.0,220.0,4.708651,-74.025696,1300000000.0,"[""https://metrocuadrado.blob.core.windows.net/...",0.0,1.0,0.0,0.0,1.0,0.0
189133,721541.0,3.0,6.0,2.0,2.0,4.0,120.0,4.680367,-74.052155,1150000000.0,"[""https://metrocuadrado.blob.core.windows.net/...",1.0,0.0,0.0,0.0,1.0,0.0
189134,721542.0,1.0,3.0,1.0,3.0,3.0,55.86,4.636661,-74.125410,260000000.0,"[""https://metrocuadrado.blob.core.windows.net/...",0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286809,1387944.0,4.0,6.0,3.0,3.0,1.0,270.0,4.660531,-74.049730,3728579250.0,"[""https://metrocuadrado.blob.core.windows.net/...",1.0,0.0,0.0,0.0,1.0,0.0
286810,1387945.0,5.0,6.0,4.0,3.0,9.0,349.0,4.659425,-74.049770,4500000000.0,"[""https://metrocuadrado.blob.core.windows.net/...",1.0,0.0,0.0,0.0,1.0,0.0
286811,1387946.0,2.0,6.0,1.0,2.0,9.0,85.0,4.660799,-74.052414,620000000.0,"[""https://metrocuadrado.blob.core.windows.net/...",0.0,0.0,0.0,1.0,1.0,0.0
286812,1387947.0,5.0,6.0,2.0,4.0,3.0,254.0,4.664576,-74.044400,2360000000.0,"[""https://metrocuadrado.blob.core.windows.net/...",0.0,0.0,0.0,1.0,1.0,0.0
286813,1387948.0,5.0,6.0,0.0,4.0,5.0,358.0,4.663999,-74.045235,3190000000.0,"[""https://metrocuadrado.blob.core.windows.net/...",1.0,0.0,0.0,0.0,1.0,0.0

In [22]:
X = data.drop(columns=["valorventa","imagenes","latitud","longitud","Casa","id"])
y = data["valorventa"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

,banos,estrato,garajes,habitaciones,piso,areaconstruida,0_5,10_20,5_10,20_mas,Apartamento
219519,4.0,6.0,4.0,4.0,5.0,392.0,0.0,1.0,0.0,0.0,1.0
208437,2.0,5.0,2.0,2.0,9.0,85.0,1.0,0.0,0.0,0.0,1.0
232515,2.0,5.0,1.0,2.0,3.0,53.0,0.0,1.0,0.0,0.0,1.0
227032,2.0,4.0,1.0,2.0,4.0,80.0,0.0,0.0,0.0,1.0,1.0
220173,3.0,5.0,2.0,3.0,11.0,110.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
243080,3.0,6.0,2.0,3.0,4.0,175.0,0.0,1.0,0.0,0.0,1.0
246302,2.0,5.0,2.0,3.0,8.0,88.0,0.0,0.0,0.0,1.0,1.0
216986,1.0,4.0,1.0,2.0,1.0,67.0,0.0,1.0,0.0,0.0,1.0
193999,2.0,4.0,1.0,2.0,2.0,81.0,0.0,1.0,0.0,0.0,1.0
266014,2.0,4.0,1.0,2.0,5.0,59.0,1.0,0.0,0.0,0.0,1.0

In [23]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(2, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
rf = RandomForestRegressor(random_state = 42)

In [25]:
from sklearn.model_selection import RandomizedSearchCV
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 500, cv = 10, verbose=2, random_state=42, n_jobs = -1)
rf_random.fit(X_train,y_train)
print(rf_random.best_params_)
print(rf_random.best_score_)
model=rf_random.best_estimator_

Fitting 10 folds for each of 500 candidates, totalling 5000 fits

KeyboardInterrupt: